config/routes.rb
Rails.application.routes.draw do

  root 'staticpages#top'
  get '/posts', to: 'posts#index'
  resources :actors, only: %i[index show create new] do
    resources :posts, only: %i[create], shallow: true do
      resources :likes, only: %i[create]
    end
  end
  # post 'like', to: 'likes#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :posts
  validates :name, presence: true, uniqueness: true
  validates :wiki_url, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :actor
  has_many :likes

  validates :film_title, presence: true
  validates :scene, presence: true, uniqueness: true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[show]
  
  def index
    @actors = Actor.all
    @actor = Actor.new
  end

  def show
    @post = Post.new
    @posts = @actor.posts.order(created_at: :desc)
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(actor_params)
    @actor.wiki_url = "https://ja.wikipedia.org/wiki/#{@actor.name}"
    if @actor.save
      redirect_to actor_path(@actor.id), success: "あぁ！#{@actor.name}を忘れるなんてどうかしてた。ついでに好きなシーンも追加してくれると嬉しいな。"
    else
      flash.now[:danger] = 'ごめん！追加できなかった！'
      render :new
    end
  end

  private
  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create!
    redirect_back fallback_location: @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:likes,:actor).sort {|a,b| b.likes.size <=> a.likes.size}
  end
  
  def create
    @actor = Actor.find(params[:actor_id])
    @post = @actor.posts.build(post_params)
    @post.author = '匿名希望' if @post.author.blank?
    if @post.save
      redirect_to actor_path(@actor), success: '投稿ありがとう。想いは受け取った！'
    else
      redirect_to actor_path(@actor), danger: 'ごめん！追加出来なかった！'
    end
  end

  private
  def post_params
    params.require(:post).permit(:film_title, :scene, :author)
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/_actor.html.erb
<tbody>
  <tr>
    <td>
      <%= link_to actor.name, actor_path(actor), class: "edit-link" %>
    </td>
    <td>
      <%= actor.posts.count %>
    </td>
  </tr>
</tbody>

app/views/actors/_form.html.erb
<div class="row mb-5 mt-1">
  <div class="col-lg-10 offset-lg-1 rounded py-3" style="background-color:#7c9377; color:#f7edd9; font-family: 'Sawarabi Mincho', sans-serif; backg">
    <div class="text-center">
      <h4><%= t('defaullts.add_actor') %></h4>
    </div>
    <%= form_with model: actor, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name %><span class="badge badge-dark ml-2"></span>
        <%= f.text_field :name, class: 'form-control', id: 'js-new-actor-name',placeholder: t('defaults.add_example_ph') %>
      </div>
      <p class="text-center"><%= t('defaults.add_caution_ph') %></p>
      <%= f.submit t('defaults.add_actor_submit'),class: 'btn btn-outline-light' %>
    <% end %>
  </div>
</div>

app/views/actors/index.html.erb
<%# <% content_for(:title, t('.title')) %>
<div class="container mt-3 mb-5 pt-5">
  <div class="row justify-content-center mb-5" style="font-family: 'Nothing You Could Do', cursive;">
    <h1><%= t('.title') %></h1>
  </div>
  <%# <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_form' 
    </div>
  </div> %>
  <div class="row pt-1 justify-content-center">
    <div class="col-md-8">
      <table class="table table-hover table-borderless t-5 " style="font-family: 'Sawarabi Mincho', sans-serif; backg">
        <thead>
        <tr style="background-color:#54724f; color:#f7edd9;">
          <th scope="col">Actor</th>
          <th scope="col">Scenes</th>
        </tr>
        </thead>
        <%= render @actors %>
      </table>
    </div>
  </div>

  <div class="row pt-1 justify-content-center">
    <div class="col-md-8">
    <p class="mt-3 text-center"><%= t('.add_message_html') %></p>
      <%= render 'form', actor: @actor %>
    </div>
  </div>
  <%# <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
      <%= paginate @users >
    </div>
  </div> %>
</div>

app/views/actors/new.html.erb
<div class="container mt-3 mb-5 pt-5">
  <div class="row justify-content-center mb-5" style="font-family: 'Nothing You Could Do', cursive;">
    <h1><%= t('.title') %></h1>
  </div>
  <div class="row pt-1 justify-content-center">
    <div class="col-md-8">
      <%= render 'form', actor: @actor %>
    </div>
  </div>
</div>

app/views/actors/show.html.erb
<div class="container mt-3 mb-5 pt-5">
  <div class="row justify-content-center mb-5" style="font-family: 'Sawarabi Mincho', sans-serif; backg">
    <h1><%= @actor.name %></h1>
  </div>
    <h5 class=" row justify-content-center">
      <%= link_to @actor.wiki_url, target: :_blank, rel: "noopener noreferrer", class: "bulb-size" do %>
        <i class="fas fa-user-secret bulb ml-4"></i>
        <p class="bulb-font-size"><u><%= Actor.human_attribute_name(:wiki_url) %></u></p>
      <% end %>
    </h5>
  </div>
  <%= render 'posts/posts', {posts: @posts } %>
  <%= render 'posts/form', { actor: @actor, post: @post } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= favicon_link_tag('favicon.ico') %>
    <title>FILMoment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body style='background-color: #fdf9f2;'>
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/likes/create.js.erb
$("#js-post-<%= @post.id %>").replaceWith("<%= j(render 'posts/posts', post: @post) %>");

app/views/posts/_form.html.erb
<div class="row mb-5 mt-5">
  <div class="col-lg-8 offset-lg-2 rounded py-3" style="background-color:#7c9377; color:#f7edd9; font-family: 'Sawarabi Mincho', sans-serif; backg">
    <div class="text-center">
      <h4><%= t('defaults.post_form_title') %></h4>
    </div>
    <%= form_with model: post, url:[actor, post], id: "new_post", local: true do |f| %><%#idを付与しているのは下のエラーメッセージのパーシャルの位置を判定するため %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :scene %><span class="badge badge-dark ml-2"><%= t('defaults.required') %></span>
        <%= f.text_area :scene, class: 'form-control', id: 'js-new-post-scene', row: 4, placeholder: t('defaults.post_scene_ph') %>
      </div>
      <div class="form-group">
        <%= f.label :film_title %><span class="badge badge-dark ml-2"><%= t('defaults.required') %></span>
        <%= f.text_field :film_title, class: 'form-control', id: 'js-new-post-title', placeholder: Post.human_attribute_name(:film_title) %>
      </div>
      <div class="form-group">
        <%= f.label :author %>
        <%= f.text_field :author, class: 'form-control', id: 'js-new-post-author', placeholder: Post.human_attribute_name(:author) %>
      </div>
      <%= f.submit t('defaults.post_submit'),class: 'btn btn-outline-light' %>
    <% end %>
  </div>
</div>

app/views/posts/_like_post.html.erb
<tr id="post-<%= post.id %>">
  <td class="pb-2">
    <div id="js-post-<%= post.id %>" class="pb-1 post-scene">
      <%= simple_format(post.scene) %>
    </div>
    <h3 class="small"><%= post.film_title %>／<%= post.author %> - <%= link_to post.actor.name, actor_path(post.actor), class: "edit-link-with-u" %></h3>
  </td>
  <td>
    <div class="list-inline justify-content-center mr-4 mt-2" style="float: right;">
        <%= link_to post_likes_path(post), method: post, remote: true do %>
          <i class="far fa-heart size"></i>
        <% end %>
        <h3 class="small mt-2 ml-1 likes"><%= post.likes.count %></h3>
  </td>
</tr>

app/views/posts/_like_posts.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <table id="js-table-comment" class="table table-striped table-hover table-borderless" style="font-family: 'Sawarabi Mincho', sans-serif; backg">
    <thead>
        <tr style="background-color:#54724f; color:#f7edd9;">
          <th>
            <%= t('defaults.th_scene') %>
            <h3 class="small"><%= t('defaults.th_info_like') %></h3>
          </th>
          <th class="post-like-td">
            <div class="list-inline justify-content-center mb-1 mr-3" style="float: right;">
                <%= t('defaults.th_like_html') %>
            </div>
          </th>
        </tr>
      </thead>
      <% posts.each do |post| %>
        <%= render partial: 'like_post', locals: {post: post} %>
      <% end %>
    </table>
  </div>
</div>

app/views/posts/_post.html.erb
<tr id="post-<%= post.id %>">
  <td class="pb-2">
    <div id="js-post-<%= post.id %>" class="pb-1 post-scene">
      <%= simple_format(post.scene) %>
    </div>
    <h3 class="small"><%= post.film_title %>／<%= post.author %></h3>
  </td>
  <td>
    <div class="list-inline justify-content-center mr-4 mt-2" style="float: right;">
        <%= link_to post_likes_path(post), method: post, remote: true do %>
          <i class="far fa-heart size"></i>
        <% end %>
        <h3 class="small mt-2 ml-1 likes"><%= post.likes.count %></h3>
  </td>
</tr>

app/views/posts/_posts.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <table id="js-table-comment" class="table table-striped table-hover table-borderless" style="font-family: 'Sawarabi Mincho', sans-serif; backg">
    <thead>
        <tr style="background-color:#54724f; color:#f7edd9;">
          <th>
            <%= t('defaults.th_scene') %>
            <h3 class="small"><%= t('defaults.th_info_post') %></h3>
          </th>
          <th class="post-like-td">
            <div class="list-inline justify-content-center mb-1 mr-3" style="float: right;">
                <%= t('defaults.th_like_html') %>
            </div>
          </th>
        </tr>
      </thead>
      <%= render posts %>
    </table>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-3 mb-5 pt-5">
  <div class="row justify-content-center mb-5" style="font-family: 'Nothing You Could Do', cursive;">
    <h1><%= t('.title') %></h1>
  </div>
  <%= render 'posts/like_posts', {posts: @posts } %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages. each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom' style="background-color:#54724f; color:#f7edd9;">
  <div class='container'>
    <div class='row  justify-content-center text-center'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p class="mb-0">Copyright © 2021. Miya</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-dark' style='background-color:#54724f'>
    <%= link_to root_path, class: 'navbar-brand' do %>
      <span style="font-family: 'Nothing You Could Do', cursive; color: #f7edd9">FILMoment</span>
    <% end %>
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ml-auto main-nav align-items-center' style="font-family: 'Nothing You Could Do', cursive;">
        <li class='nav-item'>
          <%= link_to t('actors.index.title'), actors_path, class: 'nav-link' %>
        </li>

        <li class='nav-item'>
          <%= link_to t('posts.index.title'), posts_path, class: 'nav-link' %>
        </li>

        <li class='nav-item'>
          <%= link_to t('actors.new.title'), new_actor_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/staticpages/top.html.erb
<div class="top-wrapper">
  <div class="jumbotron jumbotron-fluid mb-0">
    <div class='top-inner-text'>
      <div class="row justify-content-center" style="font-family: 'Nothing You Could Do', cursive; color:#54724f;">
        <p class="title"><%= t('.title') %></p>
      </div>
      <div class="row justify-content-center" style="font-family: 'Sawarabi Mincho', sans-serif;">
        <p class="subtitle"><%= t('.introduction') %></p>
      </div>
      <div class="row justify-content-center mt-1">
        <%= link_to posts_path do %>
          <button type="button" class="btn btn-warning bd"><%= t('.into_btn') %></button>
        <% end %>
      </div>
    </div>
  </div>
</div>